SET IDENTITY_INSERT [dbo].[Employee] ON
INSERT INTO [dbo].[Employee] ([Id], [Name], [Age], [Salary], [DepartmentID], [CompanyID]) VALUES (1, N'Arley', 30, 30000, 1, 1)
INSERT INTO [dbo].[Employee] ([Id], [Name], [Age], [Salary], [DepartmentID], [CompanyID]) VALUES (2, N'Addison', 31, 40000, 2, 1)
INSERT INTO [dbo].[Employee] ([Id], [Name], [Age], [Salary], [DepartmentID], [CompanyID]) VALUES (3, N'Axton', 27, 27000, 1, 1)
INSERT INTO [dbo].[Employee] ([Id], [Name], [Age], [Salary], [DepartmentID], [CompanyID]) VALUES (4, N'Baylor', 21, 23000, 3, 1)
INSERT INTO [dbo].[Employee] ([Id], [Name], [Age], [Salary], [DepartmentID], [CompanyID]) VALUES (5, N'Bill', 44, 31000, 4, 1)
INSERT INTO [dbo].[Employee] ([Id], [Name], [Age], [Salary], [DepartmentID], [CompanyID]) VALUES (6, N'Brandon', 40, 17000, 5, 1)
INSERT INTO [dbo].[Employee] ([Id], [Name], [Age], [Salary], [DepartmentID], [CompanyID]) VALUES (7, N'Chadwick', 32, 15000, 6, 1)
INSERT INTO [dbo].[Employee] ([Id], [Name], [Age], [Salary], [DepartmentID], [CompanyID]) VALUES (8, N'Doane', 30, 28000, 2, 1)
INSERT INTO [dbo].[Employee] ([Id], [Name], [Age], [Salary], [DepartmentID], [CompanyID]) VALUES (9, N'Easton', 28, 30000, 4, 1)
INSERT INTO [dbo].[Employee] ([Id], [Name], [Age], [Salary], [DepartmentID], [CompanyID]) VALUES (10, N'Gary', 29, 45000, 5, 1)
INSERT INTO [dbo].[Employee] ([Id], [Name], [Age], [Salary], [DepartmentID], [CompanyID]) VALUES (11, N'Granger', 30, 46000, 6, 1)
INSERT INTO [dbo].[Employee] ([Id], [Name], [Age], [Salary], [DepartmentID], [CompanyID]) VALUES (12, N'Hazelton', 24, 32000, 6, 1)
INSERT INTO [dbo].[Employee] ([Id], [Name], [Age], [Salary], [DepartmentID], [CompanyID]) VALUES (13, N'Hilton', 19, 18000, 4, 1)
SET IDENTITY_INSERT [dbo].[Employee] OFF
